// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that recommends personalized projects to integrate web development and AI skills, aligning with career goals.
 *
 * - projectRecommendation - A function that handles the project recommendation process.
 * - ProjectRecommendationInput - The input type for the projectRecommendation function.
 * - ProjectRecommendationOutput - The return type for the projectRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProjectRecommendationInputSchema = z.object({
  careerGoals: z
    .string()
    .describe('Description of your career goals, preferences and interests.'),
  webDevelopmentSkills: z.string().describe('List of your web development skills.'),
  aiSkills: z.string().describe('List of your AI and machine learning skills.'),
});
export type ProjectRecommendationInput = z.infer<typeof ProjectRecommendationInputSchema>;

const ProjectRecommendationOutputSchema = z.object({
  projectName: z.string().describe('The name of the recommended project.'),
  projectDescription: z
    .string()
    .describe('A detailed description of the recommended project.'),
  technologiesUsed: z.string().describe('List of technologies that should be used.'),
  integrationDetails: z
    .string()
    .describe(
      'Details on how to integrate web development and AI skills into the project.'
    ),
  alignmentExplanation: z
    .string()
    .describe('Explanation of how the project aligns with the career goals.'),
});
export type ProjectRecommendationOutput = z.infer<typeof ProjectRecommendationOutputSchema>;

export async function projectRecommendation(
  input: ProjectRecommendationInput
): Promise<ProjectRecommendationOutput> {
  return projectRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'projectRecommendationPrompt',
  input: {schema: ProjectRecommendationInputSchema},
  output: {schema: ProjectRecommendationOutputSchema},
  prompt: `You are an AI project recommendation expert. You will suggest a project that integrates web development and AI skills, aligning with the user's career goals.

  Career Goals: {{{careerGoals}}}
  Web Development Skills: {{{webDevelopmentSkills}}}
  AI Skills: {{{aiSkills}}}

  Based on the provided information, suggest a project that effectively combines web development and AI skills to help the user achieve their career goals. The project must be innovative and practical.

  Consider the following:
  - The project should leverage both web development and AI skills.
  - The project should align with the user's career goals.
  - Provide a detailed description of the project, including the technologies to be used and how the skills can be integrated.
  - Explain how the project helps in achieving the career goals.
  `,
});

const projectRecommendationFlow = ai.defineFlow(
  {
    name: 'projectRecommendationFlow',
    inputSchema: ProjectRecommendationInputSchema,
    outputSchema: ProjectRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
